project_id = "yrhwzmkenjgiujhofucx"

[functions.send-tournament-email]
verify_jwt = false

[functions.rotate-season]
verify_jwt = false

[functions.award-season-points]
verify_jwt = false

[functions.generate-media-image]
verify_jwt = false