// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// supabase/functions/_shared/mcp-tools/get-me.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";

// supabase/functions/_shared/mcp-tools/_shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const svc = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const token = ctx.getToken();
  if (svc && token === svc) {
    return createClient(url, svc, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
  }
  const anonKey = process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, anonKey, {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseServiceRole() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
  }
  return null;
}
function toolError(err, name) {
  const msg = err && typeof err === "object" && "message" in err ? String(err.message) : String(err);
  console.error(`[fgn-mcp] ${name} failed`, msg);
  return { content: [{ type: "text", text: msg || "tool execution failed" }], isError: true };
}
function okJson(payload, key) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: { [key]: payload }
  };
}
function parseIsoWithOffset(input) {
  const trimmed = input.trim();
  const hasOffset = /(Z|[+-]\d{2}:?\d{2})$/i.test(trimmed);
  if (!hasOffset) {
    throw new Error(
      `scheduled_at must be an ISO 8601 timestamp with an explicit timezone offset (e.g. 2026-07-24T14:00:00Z or 2026-07-24T14:00:00-05:00). Received: ${input}`
    );
  }
  const d = new Date(trimmed);
  if (Number.isNaN(d.getTime())) {
    throw new Error(`Invalid ISO 8601 timestamp: ${input}`);
  }
  return d;
}

// supabase/functions/_shared/mcp-tools/get-me.ts
var get_me_default = defineTool({
  name: "get_me",
  title: "Get my profile",
  description: "Returns the signed-in user's profile (display name, email, points, tenant).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    try {
      if (!ctx.isAuthenticated()) {
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      }
      const supabase = supabaseForUser(ctx);
      const userId = ctx.getUserId();
      const { data: userData } = await supabase.auth.getUser();
      const email = userData?.user?.email ?? null;
      const { data, error } = await supabase.from("profiles").select("id, user_id, display_name, discord_username, gamer_tag, avatar_url").eq("user_id", userId).maybeSingle();
      if (error) {
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      if (!data) {
        console.warn("[fgn-mcp] get_me: no profiles row for user_id", userId);
      }
      const { data: scoreRows } = await supabase.from("season_scores").select("points, points_available").eq("user_id", userId);
      const points = (scoreRows ?? []).reduce((sum, r) => sum + (r.points ?? 0), 0);
      const points_available = (scoreRows ?? []).reduce((sum, r) => sum + (r.points_available ?? 0), 0);
      const profileBase = data ?? {
        id: userId,
        user_id: userId,
        display_name: null,
        discord_username: null,
        gamer_tag: null,
        avatar_url: null
      };
      const profile = { ...profileBase, email, points, points_available };
      return {
        content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
        structuredContent: { profile }
      };
    } catch (err) {
      console.error("[fgn-mcp] get_me failed", err?.message, err?.stack);
      return {
        content: [{ type: "text", text: err?.message ?? "tool execution failed" }],
        isError: true
      };
    }
  }
});

// supabase/functions/_shared/mcp-tools/list-tournaments.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var list_tournaments_default = defineTool2({
  name: "list_tournaments",
  title: "List tournaments",
  description: "List tournaments visible to the signed-in user, ordered by start date descending. Excludes archived tournaments.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    try {
      if (!ctx.isAuthenticated()) {
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      }
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.from("tournaments").select("id, name, game, status, start_date, end_date").is("archived_at", null).order("start_date", { ascending: false }).limit(limit ?? 20);
      if (error) {
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      const tournaments = (data ?? []).map((t) => ({
        id: t.id,
        name: t.name,
        game: t.game,
        status: t.status,
        starts_at: t.start_date,
        ends_at: t.end_date
      }));
      return {
        content: [{ type: "text", text: JSON.stringify(tournaments, null, 2) }],
        structuredContent: { tournaments }
      };
    } catch (err) {
      console.error("[fgn-mcp] list_tournaments failed", err?.message, err?.stack);
      return {
        content: [{ type: "text", text: err?.message ?? "tool execution failed" }],
        isError: true
      };
    }
  }
});

// supabase/functions/_shared/mcp-tools/list-challenges.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_challenges_default = defineTool3({
  name: "list_challenges",
  title: "List challenges",
  description: "List challenges visible to the signed-in user. Optionally filter by game_id and is_active. Inactive challenges are only returned when the caller is a moderator or admin.",
  inputSchema: {
    game_id: z2.string().uuid().optional().describe("Filter by game UUID."),
    is_active: z2.boolean().optional().describe("Filter by active flag."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ game_id, is_active, limit }, ctx) => {
    try {
      if (!ctx.isAuthenticated()) {
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      }
      const supabase = supabaseForUser(ctx);
      let q = supabase.from("challenges").select("id, name, game_id, is_active, points_reward, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
      if (game_id !== void 0) q = q.eq("game_id", game_id);
      if (is_active !== void 0) q = q.eq("is_active", is_active);
      const { data, error } = await q;
      if (error) {
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        structuredContent: { challenges: data ?? [] }
      };
    } catch (err) {
      console.error("[fgn-mcp] list_challenges failed", err?.message, err?.stack);
      return {
        content: [{ type: "text", text: err?.message ?? "tool execution failed" }],
        isError: true
      };
    }
  }
});

// supabase/functions/_shared/mcp-tools/get-challenge.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var get_challenge_default = defineTool4({
  name: "get_challenge",
  title: "Get challenge",
  description: "Fetch a single challenge by id along with its ordered tasks (including verification_type).",
  inputSchema: {
    id: z3.string().uuid().describe("Challenge UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    try {
      if (!ctx.isAuthenticated()) {
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      }
      const supabase = supabaseForUser(ctx);
      const [challengeRes, tasksRes] = await Promise.all([
        supabase.from("challenges").select("*").eq("id", id).maybeSingle(),
        supabase.from("challenge_tasks").select(
          "id, challenge_id, title, description, display_order, verification_type, steam_achievement_api_name, steam_playtime_minutes"
        ).eq("challenge_id", id).order("display_order", { ascending: true })
      ]);
      if (challengeRes.error) {
        return { content: [{ type: "text", text: challengeRes.error.message }], isError: true };
      }
      if (!challengeRes.data) {
        return { content: [{ type: "text", text: "Challenge not found" }], isError: true };
      }
      if (tasksRes.error) {
        return { content: [{ type: "text", text: tasksRes.error.message }], isError: true };
      }
      const payload = { challenge: challengeRes.data, tasks: tasksRes.data ?? [] };
      return {
        content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
        structuredContent: payload
      };
    } catch (err) {
      console.error("[fgn-mcp] get_challenge failed", err?.message, err?.stack);
      return {
        content: [{ type: "text", text: err?.message ?? "tool execution failed" }],
        isError: true
      };
    }
  }
});

// supabase/functions/_shared/mcp-tools/list-games.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_games_default = defineTool5({
  name: "list_games",
  title: "List games",
  description: "List active games in the catalog with id, name, slug, category, and platform tags.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    try {
      if (!ctx.isAuthenticated()) {
        return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
      }
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.from("games").select("id, name, slug, category, platform_tags, is_active, display_order").order("display_order", { ascending: true }).order("name", { ascending: true }).limit(limit ?? 50);
      if (error) {
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        structuredContent: { games: data ?? [] }
      };
    } catch (err) {
      console.error("[fgn-mcp] list_games failed", err?.message, err?.stack);
      return {
        content: [{ type: "text", text: err?.message ?? "tool execution failed" }],
        isError: true
      };
    }
  }
});

// supabase/functions/_shared/mcp-tools/list-tenants.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_tenants_default = defineTool6({
  name: "list_tenants",
  title: "List my tenants",
  description: "List tenants the signed-in user belongs to (via tenant_admins). Returns brand-kit summary (primary/accent colors, logo), tenant timezone, and the connected social platform labels available for scheduled posts on that tenant.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      const supabase = supabaseForUser(ctx);
      const uid = ctx.getUserId();
      const { data: memberships, error: memErr } = await supabase.from("tenant_admins").select("tenant_id, role").eq("user_id", uid);
      if (memErr) throw memErr;
      const tenantIds = (memberships ?? []).map((m) => m.tenant_id);
      if (tenantIds.length === 0) return okJson([], "tenants");
      const { data: tenants, error: tErr } = await supabase.from("tenants").select("id, name, slug, logo_url, primary_color, accent_color, timezone, status").in("id", tenantIds);
      if (tErr) throw tErr;
      const { data: conns } = await supabase.from("social_connections").select("tenant_id, platform, account_name, is_active").in("tenant_id", tenantIds);
      const roleByTenant = /* @__PURE__ */ new Map();
      (memberships ?? []).forEach((m) => roleByTenant.set(m.tenant_id, m.role));
      const platformsByTenant = /* @__PURE__ */ new Map();
      (conns ?? []).forEach((c) => {
        if (c.is_active === false) return;
        const arr = platformsByTenant.get(c.tenant_id) ?? [];
        arr.push({ platform: c.platform, account_name: c.account_name ?? null });
        platformsByTenant.set(c.tenant_id, arr);
      });
      const result = (tenants ?? []).map((t) => ({
        id: t.id,
        name: t.name,
        slug: t.slug,
        logo_url: t.logo_url,
        primary_color: t.primary_color,
        accent_color: t.accent_color,
        timezone: t.timezone ?? "UTC",
        status: t.status,
        my_role: roleByTenant.get(t.id) ?? null,
        connected_platforms: platformsByTenant.get(t.id) ?? []
      }));
      return okJson(result, "tenants");
    } catch (err) {
      return toolError(err, "list_tenants");
    }
  }
});

// supabase/functions/_shared/mcp-tools/get-brand-kit.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
var get_brand_kit_default = defineTool7({
  name: "get_brand_kit",
  title: "Get tenant brand kit",
  description: "Return the tenant's brand kit: colors, logo, connected social platforms, and stored timezone. Caller must be a member of the tenant.",
  inputSchema: {
    tenant_id: z5.string().uuid().describe("The tenant UUID (from list_tenants).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tenant_id }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      const supabase = supabaseForUser(ctx);
      const { data: tenant, error } = await supabase.from("tenants").select("id, name, slug, logo_url, primary_color, accent_color, timezone, contact_email").eq("id", tenant_id).maybeSingle();
      if (error) throw error;
      if (!tenant) return { content: [{ type: "text", text: "Tenant not found or access denied" }], isError: true };
      const { data: conns } = await supabase.from("social_connections").select("platform, account_name, is_active").eq("tenant_id", tenant_id);
      const brand_kit = {
        tenant_id: tenant.id,
        tenant_name: tenant.name,
        slug: tenant.slug,
        logo_url: tenant.logo_url,
        primary_color: tenant.primary_color,
        accent_color: tenant.accent_color,
        timezone: tenant.timezone ?? "UTC",
        contact_email: tenant.contact_email,
        connected_platforms: (conns ?? []).filter((c) => c.is_active !== false).map((c) => ({ platform: c.platform, account_name: c.account_name ?? null })),
        voice_notes: null,
        banned_words: [],
        hashtags: []
      };
      return okJson(brand_kit, "brand_kit");
    } catch (err) {
      return toolError(err, "get_brand_kit");
    }
  }
});

// supabase/functions/_shared/mcp-tools/list-upcoming-events.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z6 } from "npm:zod@^3.25.76";
var list_upcoming_events_default = defineTool8({
  name: "list_upcoming_events",
  title: "List upcoming events for a tenant",
  description: "List upcoming tournaments and tenant events within the next N days for a tenant the caller belongs to.",
  inputSchema: {
    tenant_id: z6.string().uuid(),
    days: z6.number().int().min(1).max(180).optional().describe("Look-ahead window in days (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tenant_id, days }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      const supabase = supabaseForUser(ctx);
      const windowDays = days ?? 30;
      const now = /* @__PURE__ */ new Date();
      const until = new Date(now.getTime() + windowDays * 864e5).toISOString();
      const { data: events } = await supabase.from("tenant_events").select("id, name, description, start_date, end_date, image_url, is_public").eq("tenant_id", tenant_id).gte("start_date", now.toISOString()).lte("start_date", until).order("start_date");
      const { data: tournaments } = await supabase.from("tournaments").select("id, name, game, start_date, end_date, image_url, status").gte("start_date", now.toISOString()).lte("start_date", until).is("archived_at", null).order("start_date");
      return okJson(
        {
          tenant_events: events ?? [],
          tournaments: tournaments ?? []
        },
        "upcoming"
      );
    } catch (err) {
      return toolError(err, "list_upcoming_events");
    }
  }
});

// supabase/functions/_shared/mcp-tools/list-platform-templates.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z7 } from "npm:zod@^3.25.76";
var list_platform_templates_default = defineTool9({
  name: "list_platform_templates",
  title: "List platform marketing templates",
  description: "List published platform-wide marketing templates and universal assets the agent can clone into a tenant's private library. When tenant_id is supplied, each row includes `adopted` and `adopted_asset_id` so slate runs can propose localized treatments only for unadopted universal assets. Universal-only mode via universal_only=true.",
  inputSchema: {
    tenant_id: z7.string().uuid().optional(),
    universal_only: z7.boolean().optional(),
    limit: z7.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tenant_id, universal_only, limit }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      const supabase = supabaseForUser(ctx);
      let q = supabase.from("marketing_assets").select("id, campaign_id, file_path, url, label, width, height, display_order, created_at, is_universal, universal_published_at, universal_title, universal_campaign_context, usage_notes").order("created_at", { ascending: false }).limit(limit ?? 30);
      if (universal_only) q = q.eq("is_universal", true);
      const { data, error } = await q;
      if (error) throw error;
      let adoptionByAsset = {};
      if (tenant_id && data && data.length > 0) {
        const ids = data.map((r) => r.id);
        const { data: adoptions } = await supabase.from("tenant_marketing_assets").select("id, source_asset_id").eq("tenant_id", tenant_id).in("source_asset_id", ids);
        for (const a of adoptions ?? []) {
          adoptionByAsset[a.source_asset_id] = {
            adopted: true,
            adopted_asset_id: a.id
          };
        }
      }
      const enriched = (data ?? []).map((r) => ({
        ...r,
        adopted: tenant_id ? Boolean(adoptionByAsset[r.id]) : void 0,
        adopted_asset_id: tenant_id ? adoptionByAsset[r.id]?.adopted_asset_id ?? null : void 0
      }));
      return okJson(enriched, "templates");
    } catch (err) {
      return toolError(err, "list_platform_templates");
    }
  }
});

// supabase/functions/_shared/mcp-tools/list-tenant-assets.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z8 } from "npm:zod@^3.25.76";
var list_tenant_assets_default = defineTool10({
  name: "list_tenant_assets",
  title: "List tenant marketing assets",
  description: "List assets in a tenant's private branded marketing library. Optionally filter to published-only or agent-authored.",
  inputSchema: {
    tenant_id: z8.string().uuid(),
    published_only: z8.boolean().optional(),
    agent_only: z8.boolean().optional(),
    limit: z8.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tenant_id, published_only, agent_only, limit }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      const supabase = supabaseForUser(ctx);
      let q = supabase.from("tenant_marketing_assets").select("id, tenant_id, campaign_id, file_name, url, label, is_published, agent_source, source_url, proposed_by, notes, created_at, updated_at").eq("tenant_id", tenant_id).order("created_at", { ascending: false }).limit(limit ?? 50);
      if (published_only) q = q.eq("is_published", true);
      if (agent_only) q = q.not("agent_source", "is", null);
      const { data, error } = await q;
      if (error) throw error;
      return okJson(data ?? [], "assets");
    } catch (err) {
      return toolError(err, "list_tenant_assets");
    }
  }
});

// supabase/functions/_shared/mcp-tools/list-pending-agent-drafts.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z9 } from "npm:zod@^3.25.76";
var list_pending_agent_drafts_default = defineTool11({
  name: "list_pending_agent_drafts",
  title: "List pending and rejected agent drafts",
  description: "For a tenant, list agent-authored campaigns and scheduled posts that are currently 'pending_review', plus any 'rejected' rows updated in the last 30 days (with feedback notes). Use this each turn to prioritize revisions before proposing new work.",
  inputSchema: {
    tenant_id: z9.string().uuid()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tenant_id }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      const supabase = supabaseForUser(ctx);
      const thirtyDaysAgo = new Date(Date.now() - 30 * 864e5).toISOString();
      const { data: campaigns, error: cErr } = await supabase.from("marketing_campaigns").select("id, title, description, social_copy, status, feedback_note, target_platforms, source_event_id, source_tournament_id, agent_source, proposed_by, created_at, updated_at").eq("tenant_id", tenant_id).not("agent_source", "is", null).or(`status.eq.pending_review,and(status.eq.rejected,updated_at.gte.${thirtyDaysAgo})`).order("updated_at", { ascending: false });
      if (cErr) throw cErr;
      const { data: posts, error: pErr } = await supabase.from("scheduled_posts").select("id, campaign_id, platform, caption, image_url, scheduled_at, status, feedback_note, agent_source, proposed_by, created_at, updated_at").eq("tenant_id", tenant_id).not("agent_source", "is", null).or(`status.eq.pending_review,and(status.eq.rejected,updated_at.gte.${thirtyDaysAgo})`).order("updated_at", { ascending: false });
      if (pErr) throw pErr;
      return okJson(
        {
          campaigns: (campaigns ?? []).map((r) => ({ kind: "campaign", ...r })),
          scheduled_posts: (posts ?? []).map((r) => ({ kind: "scheduled_post", ...r }))
        },
        "drafts"
      );
    } catch (err) {
      return toolError(err, "list_pending_agent_drafts");
    }
  }
});

// supabase/functions/_shared/mcp-tools/create-campaign-draft.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z10 } from "npm:zod@^3.25.76";
var create_campaign_draft_default = defineTool12({
  name: "create_campaign_draft",
  title: "Create marketing campaign draft",
  description: "Create a draft marketing campaign for a tenant. Status is always 'pending_review'; a tenant admin must approve before anything publishes. Pass source_event_id or source_tournament_id (mutually exclusive) from list_upcoming_events to build off an existing event, or omit both to start a new standalone campaign. Supply idempotency_key to make retries safe.",
  inputSchema: {
    tenant_id: z10.string().uuid(),
    title: z10.string().min(1),
    description: z10.string().optional(),
    social_copy: z10.string().optional(),
    category: z10.string().optional().describe("Campaign category (default 'social_media')."),
    target_platforms: z10.array(z10.string()).optional(),
    source_event_id: z10.string().uuid().optional().describe("tenant_events.id when the campaign promotes a tenant event."),
    source_tournament_id: z10.string().uuid().optional().describe("tournaments.id when the campaign promotes a tournament."),
    idempotency_key: z10.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      if (input.source_event_id && input.source_tournament_id) {
        return { content: [{ type: "text", text: "Pass at most one of source_event_id or source_tournament_id." }], isError: true };
      }
      const supabase = supabaseForUser(ctx);
      const uid = ctx.getUserId();
      if (input.idempotency_key) {
        const { data: existing } = await supabase.from("marketing_campaigns").select("*").eq("tenant_id", input.tenant_id).eq("idempotency_key", input.idempotency_key).maybeSingle();
        if (existing) return okJson({ ...existing, _idempotent: true }, "campaign");
      }
      const { data, error } = await supabase.from("marketing_campaigns").insert({
        tenant_id: input.tenant_id,
        title: input.title,
        description: input.description ?? null,
        social_copy: input.social_copy ?? null,
        category: input.category ?? "social_media",
        target_platforms: input.target_platforms ?? [],
        status: "pending_review",
        is_published: false,
        agent_source: "claude-mcp",
        proposed_by: uid,
        created_by: uid,
        source_event_id: input.source_event_id ?? null,
        source_tournament_id: input.source_tournament_id ?? null,
        idempotency_key: input.idempotency_key ?? null
      }).select().single();
      if (error) throw error;
      return okJson(data, "campaign");
    } catch (err) {
      return toolError(err, "create_campaign_draft");
    }
  }
});

// supabase/functions/_shared/mcp-tools/update-campaign-draft.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z11 } from "npm:zod@^3.25.76";
var update_campaign_draft_default = defineTool13({
  name: "update_campaign_draft",
  title: "Update marketing campaign draft",
  description: "Revise a draft/pending_review/rejected marketing campaign. Cannot change status directly. If the campaign was rejected, address the feedback_note in your changes and follow up with propose_scheduled_post if needed.",
  inputSchema: {
    id: z11.string().uuid(),
    title: z11.string().min(1).optional(),
    description: z11.string().nullish(),
    social_copy: z11.string().nullish(),
    target_platforms: z11.array(z11.string()).optional(),
    source_event_id: z11.string().uuid().nullish().describe("Pass a tenant_events.id to link, or null to clear."),
    source_tournament_id: z11.string().uuid().nullish().describe("Pass a tournaments.id to link, or null to clear.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ id, ...fields }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      if (fields.source_event_id && fields.source_tournament_id) {
        return { content: [{ type: "text", text: "Pass at most one of source_event_id or source_tournament_id." }], isError: true };
      }
      const supabase = supabaseForUser(ctx);
      const patch = {};
      for (const [k, v] of Object.entries(fields)) if (v !== void 0) patch[k] = v;
      if (Object.keys(patch).length === 0) {
        return { content: [{ type: "text", text: "No fields provided to update." }], isError: true };
      }
      const { data, error } = await supabase.from("marketing_campaigns").update(patch).eq("id", id).select().maybeSingle();
      if (error) throw error;
      if (!data) return { content: [{ type: "text", text: "Campaign not found, not editable, or access denied." }], isError: true };
      return okJson(data, "campaign");
    } catch (err) {
      return toolError(err, "update_campaign_draft");
    }
  }
});

// supabase/functions/_shared/mcp-tools/attach-tenant-asset-draft.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z12 } from "npm:zod@^3.25.76";
var MAX_BYTES = 20 * 1024 * 1024;
var BUCKET = "tenant-marketing";
function extFromContentType(ct) {
  if (!ct) return "bin";
  const m = ct.split(";")[0].trim().toLowerCase();
  const map = {
    "image/png": "png",
    "image/jpeg": "jpg",
    "image/jpg": "jpg",
    "image/webp": "webp",
    "image/gif": "gif",
    "image/svg+xml": "svg",
    "video/mp4": "mp4"
  };
  return map[m] ?? "bin";
}
function extFromUrl(url) {
  try {
    const p = new URL(url).pathname;
    const m = p.match(/\.([a-zA-Z0-9]{2,5})$/);
    return m ? m[1].toLowerCase() : null;
  } catch {
    return null;
  }
}
var attach_tenant_asset_draft_default = defineTool14({
  name: "attach_tenant_asset_draft",
  title: "Attach agent-generated asset to tenant library",
  description: "Download the supplied image URL server-side, upload it into the tenant's private storage bucket, and insert a draft row in tenant_marketing_assets (is_published=false). The original URL is preserved on source_url for lineage; the row's url points at the permanent Supabase Storage URL. Supply campaign_id to link to a campaign.",
  inputSchema: {
    tenant_id: z12.string().uuid(),
    source_url: z12.string().url().describe("Externally reachable URL to the image (CDN links accepted; downloaded server-side)."),
    file_name: z12.string().min(1).describe("Human-readable file name for the library."),
    label: z12.string().optional().describe("Format label, e.g. 'Square 1080', 'Story 1080x1920'."),
    campaign_id: z12.string().uuid().optional(),
    source_asset_id: z12.string().uuid().optional().describe("Platform template id if this was cloned from marketing_assets."),
    notes: z12.string().optional(),
    overlay_config: z12.record(z12.any()).optional().describe("Optional editor overlay config { canvas, overlays } so the draft reopens as editable layers."),
    background_url: z12.string().url().optional().describe("Optional clean base image URL (no baked-in overlays). Editor uses this instead of the flattened url.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      const userSupabase = supabaseForUser(ctx);
      const uid = ctx.getUserId();
      const resp = await fetch(input.source_url, { redirect: "follow" });
      if (!resp.ok) {
        return { content: [{ type: "text", text: `Failed to fetch source_url: HTTP ${resp.status}` }], isError: true };
      }
      const ct = resp.headers.get("content-type");
      const cl = Number(resp.headers.get("content-length") ?? "0");
      if (cl && cl > MAX_BYTES) {
        return { content: [{ type: "text", text: `Source file too large (${cl} bytes; max ${MAX_BYTES}).` }], isError: true };
      }
      const buf = new Uint8Array(await resp.arrayBuffer());
      if (buf.byteLength > MAX_BYTES) {
        return { content: [{ type: "text", text: `Source file too large after download.` }], isError: true };
      }
      const ext = extFromUrl(input.source_url) ?? extFromContentType(ct);
      const now = /* @__PURE__ */ new Date();
      const yyyy = now.getUTCFullYear();
      const mm = String(now.getUTCMonth() + 1).padStart(2, "0");
      const uuid = crypto.randomUUID();
      const path = `${input.tenant_id}/agent/${yyyy}/${mm}/${uuid}.${ext}`;
      const uploadClient = userSupabase;
      const { error: upErr } = await uploadClient.storage.from(BUCKET).upload(path, buf, {
        contentType: ct ?? "application/octet-stream",
        upsert: false
      });
      if (upErr) {
        const svc = supabaseServiceRole();
        const retry = await svc.storage.from(BUCKET).upload(path, buf, {
          contentType: ct ?? "application/octet-stream",
          upsert: false
        });
        if (retry.error) throw retry.error;
      }
      const signTtlSeconds = 60 * 60 * 24 * 365;
      const { data: signed, error: signErr } = await userSupabase.storage.from(BUCKET).createSignedUrl(path, signTtlSeconds);
      if (signErr || !signed?.signedUrl) {
        const svc = supabaseServiceRole();
        const retry = await svc.storage.from(BUCKET).createSignedUrl(path, signTtlSeconds);
        if (retry.error || !retry.data?.signedUrl) throw signErr ?? retry.error;
        var storedUrl = retry.data.signedUrl;
      } else {
        var storedUrl = signed.signedUrl;
      }
      const { data: row, error: insErr } = await userSupabase.from("tenant_marketing_assets").insert({
        tenant_id: input.tenant_id,
        file_name: input.file_name,
        file_path: path,
        url: storedUrl,
        source_url: input.source_url,
        label: input.label ?? "Default",
        campaign_id: input.campaign_id ?? null,
        source_asset_id: input.source_asset_id ?? null,
        notes: input.notes ?? null,
        overlay_config: input.overlay_config ?? null,
        background_url: input.background_url ?? null,
        is_published: false,
        agent_source: "claude-mcp",
        proposed_by: uid,
        created_by: uid
      }).select().single();
      if (insErr) throw insErr;
      return okJson(row, "asset");
    } catch (err) {
      return toolError(err, "attach_tenant_asset_draft");
    }
  }
});

// supabase/functions/_shared/mcp-tools/propose-scheduled-post.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z13 } from "npm:zod@^3.25.76";
var propose_scheduled_post_default = defineTool15({
  name: "propose_scheduled_post",
  title: "Propose a scheduled social post",
  description: "Create a scheduled_posts row with status='pending_review'. The cron dispatcher only publishes rows with status='pending' (exact match), so agent proposals never publish without tenant-admin approval. scheduled_at MUST be ISO 8601 with an explicit timezone offset (Z or \xB1HH:MM); stored as UTC. Restrict `platform` to values returned by list_tenants.connected_platforms.",
  inputSchema: {
    tenant_id: z13.string().uuid(),
    platform: z13.string().describe("One of the tenant's connected_platforms values."),
    image_url: z13.string().url().describe("Permanent Supabase Storage URL from attach_tenant_asset_draft.url."),
    caption: z13.string().optional(),
    scheduled_at: z13.string().describe("ISO 8601 with explicit offset, e.g. 2026-07-24T14:00:00-05:00 or ...Z."),
    campaign_id: z13.string().uuid().optional(),
    connection_id: z13.string().uuid().optional(),
    idempotency_key: z13.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      const supabase = supabaseForUser(ctx);
      const uid = ctx.getUserId();
      let when;
      try {
        when = parseIsoWithOffset(input.scheduled_at);
      } catch (e) {
        return { content: [{ type: "text", text: e.message }], isError: true };
      }
      if (input.idempotency_key) {
        const { data: existing } = await supabase.from("scheduled_posts").select("*").eq("tenant_id", input.tenant_id).eq("idempotency_key", input.idempotency_key).maybeSingle();
        if (existing) return okJson({ ...existing, _idempotent: true }, "scheduled_post");
      }
      const { data, error } = await supabase.from("scheduled_posts").insert({
        tenant_id: input.tenant_id,
        user_id: uid,
        platform: input.platform,
        image_url: input.image_url,
        caption: input.caption ?? "",
        scheduled_at: when.toISOString(),
        status: "pending_review",
        agent_source: "claude-mcp",
        proposed_by: uid,
        campaign_id: input.campaign_id ?? null,
        connection_id: input.connection_id ?? null,
        idempotency_key: input.idempotency_key ?? null
      }).select().single();
      if (error) throw error;
      const { data: conflict } = await supabase.rpc("check_schedule_conflict", {
        _tenant_id: input.tenant_id,
        _platform: input.platform,
        _scheduled_at: when.toISOString(),
        _exclude_id: data.id,
        _window_seconds: 3600
      });
      return okJson({ ...data, conflict: conflict ?? null }, "scheduled_post");
    } catch (err) {
      return toolError(err, "propose_scheduled_post");
    }
  }
});

// supabase/functions/_shared/mcp-tools/update-scheduled-post.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z14 } from "npm:zod@^3.25.76";
var update_scheduled_post_default = defineTool16({
  name: "update_scheduled_post",
  title: "Update / resubmit scheduled post",
  description: "Revise a draft/pending_review/rejected scheduled post. If the row is currently 'rejected', the update flips its status back to 'pending_review' and preserves the existing feedback_note for audit. scheduled_at (if provided) MUST be ISO 8601 with explicit offset.",
  inputSchema: {
    id: z14.string().uuid(),
    platform: z14.string().optional(),
    image_url: z14.string().url().optional(),
    caption: z14.string().optional(),
    scheduled_at: z14.string().optional(),
    campaign_id: z14.string().uuid().nullish(),
    connection_id: z14.string().uuid().nullish()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ id, ...fields }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      const supabase = supabaseForUser(ctx);
      const { data: current, error: fetchErr } = await supabase.from("scheduled_posts").select("id, status").eq("id", id).maybeSingle();
      if (fetchErr) throw fetchErr;
      if (!current) return { content: [{ type: "text", text: "Scheduled post not found or access denied." }], isError: true };
      const patch = {};
      for (const [k, v] of Object.entries(fields)) {
        if (v === void 0) continue;
        if (k === "scheduled_at" && typeof v === "string") {
          try {
            patch.scheduled_at = parseIsoWithOffset(v).toISOString();
          } catch (e) {
            return { content: [{ type: "text", text: e.message }], isError: true };
          }
        } else {
          patch[k] = v;
        }
      }
      if (current.status === "rejected") {
        patch.status = "pending_review";
      }
      if (Object.keys(patch).length === 0) {
        return { content: [{ type: "text", text: "No fields provided to update." }], isError: true };
      }
      const { data, error } = await supabase.from("scheduled_posts").update(patch).eq("id", id).select().maybeSingle();
      if (error) throw error;
      if (!data) return { content: [{ type: "text", text: "Scheduled post not editable in its current state." }], isError: true };
      const { data: conflict } = await supabase.rpc("check_schedule_conflict", {
        _tenant_id: data.tenant_id,
        _platform: data.platform,
        _scheduled_at: data.scheduled_at,
        _exclude_id: data.id,
        _window_seconds: 3600
      });
      return okJson({ ...data, conflict: conflict ?? null }, "scheduled_post");
    } catch (err) {
      return toolError(err, "update_scheduled_post");
    }
  }
});

// supabase/functions/_shared/mcp-tools/list-branded-pages.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z15 } from "npm:zod@^3.25.76";
var list_branded_pages_default = defineTool17({
  name: "list_branded_pages",
  title: "List branded pages",
  description: "List every web_page belonging to a tenant: the always-on Portal Banner (is_tenant_banner=true) and any landing pages. Each row includes publish state, scheduling window, and section count so the agent can decide what to propose.",
  inputSchema: {
    tenant_id: z15.string().uuid().describe("Tenant to list pages for. REQUIRED \u2014 do not omit.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      const sb = supabaseForUser(ctx);
      const { data: pages, error } = await sb.from("web_pages").select("id, title, slug, description, is_published, is_tenant_banner, publish_at, unpublish_at, created_at, updated_at").eq("tenant_id", input.tenant_id).order("is_tenant_banner", { ascending: false }).order("updated_at", { ascending: false });
      if (error) throw error;
      const ids = (pages ?? []).map((p) => p.id);
      let counts = /* @__PURE__ */ new Map();
      if (ids.length) {
        const { data: secs } = await sb.from("web_page_sections").select("page_id").in("page_id", ids);
        for (const s of secs ?? []) {
          counts.set(s.page_id, (counts.get(s.page_id) ?? 0) + 1);
        }
      }
      const enriched = (pages ?? []).map((p) => ({ ...p, section_count: counts.get(p.id) ?? 0 }));
      return okJson(enriched, "pages");
    } catch (err) {
      return toolError(err, "list_branded_pages");
    }
  }
});

// supabase/functions/_shared/mcp-tools/list-page-templates.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z16 } from "npm:zod@^3.25.76";
var list_page_templates_default = defineTool18({
  name: "list_page_templates",
  title: "List branded-page templates",
  description: "Return curated + universal starting points for landing pages. Each template is a name, category, description, preview image URL, and a JSON array of sections you can pass to propose_branded_page.",
  inputSchema: {
    tenant_id: z16.string().uuid().optional().describe("Optional \u2014 only used to scope future tenant-private templates; universal templates are returned to all tenants."),
    category: z16.string().optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      const sb = supabaseForUser(ctx);
      let q = sb.from("web_page_templates").select("id, name, description, category, preview_image_url, sections, is_universal");
      if (input.category) q = q.eq("category", input.category);
      const { data, error } = await q.order("category", { ascending: true });
      if (error) throw error;
      return okJson(data ?? [], "templates");
    } catch (err) {
      return toolError(err, "list_page_templates");
    }
  }
});

// supabase/functions/_shared/mcp-tools/propose-branded-page.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z17 } from "npm:zod@^3.25.76";
var SectionSchema = z17.object({
  section_type: z17.enum([
    "hero",
    "text_block",
    "image_gallery",
    "cta",
    "embed_widget",
    "banner",
    "video",
    "featured_events"
  ]),
  config: z17.record(z17.any()).default({})
});
var propose_branded_page_default = defineTool19({
  name: "propose_branded_page",
  title: "Propose a branded landing page (draft)",
  description: "Create a DRAFT web_pages row for a tenant with a supplied section array. Never publishes \u2014 is_published stays false, so a tenant admin has to hit Publish in the portal. Pass either template_id (to hydrate sections from a template) or sections (direct block array). Passing both replaces the template's sections with the supplied ones.",
  inputSchema: {
    tenant_id: z17.string().uuid().describe("Owner tenant. REQUIRED."),
    title: z17.string().min(1).max(120),
    slug: z17.string().min(1).max(80).regex(/^[a-z0-9-]+$/, "slug must be lowercase kebab-case"),
    description: z17.string().max(500).optional(),
    template_id: z17.string().uuid().optional(),
    sections: z17.array(SectionSchema).max(30).optional(),
    idempotency_key: z17.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      const sb = supabaseForUser(ctx);
      const uid = ctx.getUserId();
      if (input.idempotency_key) {
        const { data: existing } = await sb.from("web_pages").select("*").eq("tenant_id", input.tenant_id).eq("slug", input.slug).maybeSingle();
        if (existing) return okJson({ ...existing, _idempotent: true }, "page");
      }
      let sections = input.sections ?? [];
      if (input.template_id && sections.length === 0) {
        const { data: tpl, error: tplErr } = await sb.from("web_page_templates").select("sections").eq("id", input.template_id).single();
        if (tplErr) throw tplErr;
        sections = tpl?.sections ?? [];
      }
      const { data: page, error: pErr } = await sb.from("web_pages").insert({
        tenant_id: input.tenant_id,
        title: input.title,
        slug: input.slug,
        description: input.description ?? null,
        is_published: false,
        created_by: uid
      }).select().single();
      if (pErr) throw pErr;
      if (sections.length) {
        const rows = sections.map((s, i) => ({
          page_id: page.id,
          section_type: s.section_type,
          display_order: i,
          config: s.config ?? {}
        }));
        const { error: sErr } = await sb.from("web_page_sections").insert(rows);
        if (sErr) throw sErr;
      }
      return okJson({
        ...page,
        section_count: sections.length,
        preview_hint: "Draft only \u2014 tenant admin must approve and publish via /tenant/marketing?tab=webpages."
      }, "page");
    } catch (err) {
      return toolError(err, "propose_branded_page");
    }
  }
});

// supabase/functions/_shared/mcp-tools/propose-portal-banner-update.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z18 } from "npm:zod@^3.25.76";
var SectionSchema2 = z18.object({
  section_type: z18.enum([
    "hero",
    "text_block",
    "image_gallery",
    "cta",
    "embed_widget",
    "banner",
    "video",
    "featured_events"
  ]),
  config: z18.record(z18.any()).default({})
});
var propose_portal_banner_update_default = defineTool20({
  name: "propose_portal_banner_update",
  title: "Propose an update to the portal-wide banner (draft only)",
  description: "Draft-edit the tenant's Portal Banner. Creates a DRAFT landing page containing the proposed banner sections; the live banner is never modified. A human must copy the approved sections into the banner via the tenant portal.",
  inputSchema: {
    tenant_id: z18.string().uuid(),
    sections: z18.array(SectionSchema2).min(1).max(10),
    proposal_reason: z18.string().min(1).max(500)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      const sb = supabaseForUser(ctx);
      const uid = ctx.getUserId();
      const slug = `portal-banner-proposal-${Date.now()}`;
      const { data: page, error: pErr } = await sb.from("web_pages").insert({
        tenant_id: input.tenant_id,
        title: "Portal Banner Proposal",
        slug,
        description: input.proposal_reason,
        is_published: false,
        created_by: uid
      }).select().single();
      if (pErr) throw pErr;
      const rows = input.sections.map((s, i) => ({
        page_id: page.id,
        section_type: s.section_type,
        display_order: i,
        config: s.config ?? {}
      }));
      const { error: sErr } = await sb.from("web_page_sections").insert(rows);
      if (sErr) throw sErr;
      return okJson({
        ...page,
        note: "This is a DRAFT proposal page, not the live banner. A tenant admin must review and copy the sections onto the Portal Banner from /tenant/marketing?tab=webpages."
      }, "proposal");
    } catch (err) {
      return toolError(err, "propose_portal_banner_update");
    }
  }
});

// supabase/functions/_shared/mcp-tools/compose-event-promo.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z19 } from "npm:zod@^3.25.76";

// src/lib/promo/composePromoLayout.ts
var PROMO_DIMENSIONS = {
  portrait: { width: 1080, height: 1350 },
  square: { width: 1080, height: 1080 },
  landscape: { width: 1200, height: 628 },
  story: { width: 1080, height: 1920 }
};
function formatDate(iso) {
  if (!iso) return "";
  try {
    const d = new Date(iso);
    return d.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
  } catch {
    return "";
  }
}
function composePromoLayout(args) {
  const format = args.format ?? "portrait";
  const dim = PROMO_DIMENSIONS[format];
  const accent = args.tenantPrimaryColor || "#22d3ee";
  const dateStr = formatDate(args.event.start_date);
  const texts = [];
  if (args.beatLabel) {
    texts.push({
      text: args.beatLabel.toUpperCase(),
      xPct: 0.06,
      yPct: 0.56,
      fontSize: 28,
      color: accent,
      fontWeight: "bold"
    });
  }
  texts.push({
    text: args.event.name.toUpperCase(),
    xPct: 0.06,
    yPct: 0.62,
    fontSize: 64,
    color: "#ffffff",
    fontWeight: "bold"
  });
  if (args.event.game) {
    texts.push({
      text: args.event.game,
      xPct: 0.06,
      yPct: 0.76,
      fontSize: 30,
      color: "#e2e8f0"
    });
  }
  if (dateStr) {
    texts.push({
      text: dateStr,
      xPct: 0.06,
      yPct: 0.83,
      fontSize: 26,
      color: "#cbd5e1"
    });
  }
  if (args.event.prize_pool) {
    texts.push({
      text: `Prize: ${args.event.prize_pool}`,
      xPct: 0.06,
      yPct: 0.9,
      fontSize: 26,
      color: accent,
      fontWeight: "bold"
    });
  }
  return {
    format,
    width: dim.width,
    height: dim.height,
    backgroundUrl: null,
    // caller fills from event.image_url — kept separate so
    // the layout is decoupled from image loading
    backgroundFallbackHex: "#0f172a",
    gradient: {
      startPct: 0.45,
      fromRgba: "rgba(0,0,0,0)",
      toRgba: "rgba(0,0,0,0.85)"
    },
    accentBar: {
      xPct: 0.04,
      yPct: 0.62,
      wPct: 8e-3,
      hPct: 0.32,
      color: accent
    },
    texts
  };
}
function promoSceneToEditorTexts(scene) {
  return scene.texts.map((t) => ({
    text: t.text,
    xPct: t.xPct,
    yPct: t.yPct,
    x: Math.round(t.xPct * scene.width),
    y: Math.round(t.yPct * scene.height),
    fontSize: t.fontSize,
    color: t.color,
    fontFamily: "sans-serif",
    fontWeight: t.fontWeight ?? "normal"
  }));
}

// supabase/functions/_shared/promo/renderPromo.ts
import { Resvg, initWasm } from "npm:@resvg/resvg-wasm@2.6.2";
var wasmReady = null;
async function ensureWasm() {
  if (!wasmReady) {
    wasmReady = (async () => {
      const res = await fetch("https://unpkg.com/@resvg/resvg-wasm@2.6.2/index_bg.wasm");
      if (!res.ok) throw new Error(`Failed to fetch resvg wasm: ${res.status}`);
      const bytes = new Uint8Array(await res.arrayBuffer());
      await initWasm(bytes);
    })();
  }
  return wasmReady;
}
function escapeXml(s) {
  return s.replace(/[<>&'"]/g, (c) => c === "<" ? "&lt;" : c === ">" ? "&gt;" : c === "&" ? "&amp;" : c === "'" ? "&apos;" : "&quot;");
}
async function fetchAsDataUrl(url) {
  try {
    const res = await fetch(url, { redirect: "follow" });
    if (!res.ok) return null;
    const ct = res.headers.get("content-type") ?? "image/jpeg";
    const buf = new Uint8Array(await res.arrayBuffer());
    let bin = "";
    for (let i = 0; i < buf.length; i++) bin += String.fromCharCode(buf[i]);
    const b64 = btoa(bin);
    return `data:${ct};base64,${b64}`;
  } catch {
    return null;
  }
}
function rgbaFromCss(rgba) {
  return rgba;
}
async function renderPromoSceneToPng(scene) {
  await ensureWasm();
  let bgHref = null;
  if (scene.backgroundUrl) {
    bgHref = await fetchAsDataUrl(scene.backgroundUrl);
  }
  const w = scene.width;
  const h = scene.height;
  const gradStartY = scene.gradient.startPct * h;
  const bgLayer = bgHref ? `<image href="${bgHref}" x="0" y="0" width="${w}" height="${h}" preserveAspectRatio="xMidYMid slice"/>` : `<rect x="0" y="0" width="${w}" height="${h}" fill="${scene.backgroundFallbackHex}"/>`;
  const gradient = `
    <defs>
      <linearGradient id="dark" x1="0" y1="${gradStartY}" x2="0" y2="${h}" gradientUnits="userSpaceOnUse">
        <stop offset="0" stop-color="${rgbaFromCss(scene.gradient.fromRgba)}"/>
        <stop offset="1" stop-color="${rgbaFromCss(scene.gradient.toRgba)}"/>
      </linearGradient>
      <filter id="drop" x="-20%" y="-20%" width="140%" height="140%">
        <feGaussianBlur in="SourceAlpha" stdDeviation="3"/>
        <feOffset dx="2" dy="2" result="off"/>
        <feComponentTransfer><feFuncA type="linear" slope="0.6"/></feComponentTransfer>
        <feMerge><feMergeNode/><feMergeNode in="SourceGraphic"/></feMerge>
      </filter>
    </defs>`;
  const overlay = `<rect x="0" y="0" width="${w}" height="${h}" fill="url(#dark)"/>`;
  const ab = scene.accentBar;
  const accent = `<rect x="${ab.xPct * w}" y="${ab.yPct * h}" width="${ab.wPct * w}" height="${ab.hPct * h}" fill="${ab.color}"/>`;
  const textNodes = scene.texts.map((t) => {
    const weight = t.fontWeight === "bold" ? "bold" : "normal";
    const y = t.yPct * h + t.fontSize * 0.85;
    return `<text x="${t.xPct * w}" y="${y}" font-family="Inter, sans-serif" font-size="${t.fontSize}" font-weight="${weight}" fill="${t.color}" filter="url(#drop)">${escapeXml(t.text)}</text>`;
  }).join("");
  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  ${gradient}
  ${bgLayer}
  ${overlay}
  ${accent}
  ${textNodes}
</svg>`;
  const resvg = new Resvg(svg, {
    background: scene.backgroundFallbackHex,
    fitTo: { mode: "width", value: w },
    font: {
      loadSystemFonts: false
      // deterministic — rely on bundled DejaVu fallback
    }
  });
  const png = resvg.render().asPng();
  return png;
}

// supabase/functions/_shared/mcp-tools/compose-event-promo.ts
var BUCKET2 = "tenant-marketing";
var compose_event_promo_default = defineTool21({
  name: "compose_event_promo",
  title: "Compose a deterministic promo image from a published event",
  description: "Lane 1 (calendar-lane) composer. Layouts an event (tournament OR tenant event) with the tenant's brand color and beat label into a PNG using pure server-side rendering (no external image generation cost), uploads it into the tenant-marketing bucket, and inserts a tenant_marketing_assets draft row identical in shape to attach_tenant_asset_draft \u2014 including overlay_config so the draft opens in the editor as separately-editable text layers. Provide exactly one of tournament_id or event_id.",
  inputSchema: {
    tenant_id: z19.string().uuid(),
    tournament_id: z19.string().uuid().optional(),
    event_id: z19.string().uuid().optional(),
    format: z19.enum(["portrait", "square", "landscape", "story"]).default("portrait"),
    beat_label: z19.string().optional().describe("e.g. 'Announce', 'Countdown', 'Day-Of', 'Recap'"),
    campaign_id: z19.string().uuid().optional(),
    file_name: z19.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    try {
      if (!!input.tournament_id === !!input.event_id) {
        return { content: [{ type: "text", text: "Provide exactly one of tournament_id or event_id." }], isError: true };
      }
      const userSupabase = supabaseForUser(ctx);
      const uid = ctx.getUserId();
      let evt;
      if (input.tournament_id) {
        const { data, error } = await userSupabase.from("tournaments").select("id, name, game, start_date, prize_pool, image_url").eq("id", input.tournament_id).maybeSingle();
        if (error) throw error;
        if (!data) return { content: [{ type: "text", text: "Tournament not found or not visible." }], isError: true };
        evt = data;
      } else {
        const { data, error } = await userSupabase.from("tenant_events").select("id, name, game, start_date, prize_pool, image_url, tenant_id").eq("id", input.event_id).maybeSingle();
        if (error) throw error;
        if (!data) return { content: [{ type: "text", text: "Event not found or not visible." }], isError: true };
        if (data.tenant_id !== input.tenant_id) {
          return { content: [{ type: "text", text: "Event does not belong to the supplied tenant_id." }], isError: true };
        }
        evt = data;
      }
      const { data: tenant } = await userSupabase.from("tenants").select("primary_color").eq("id", input.tenant_id).maybeSingle();
      const scene = composePromoLayout({
        event: {
          name: evt.name,
          game: evt.game ?? null,
          start_date: evt.start_date ?? null,
          prize_pool: evt.prize_pool ?? null
        },
        tenantPrimaryColor: tenant?.primary_color ?? null,
        format: input.format,
        beatLabel: input.beat_label ?? null
      });
      scene.backgroundUrl = evt.image_url ?? null;
      const png = await renderPromoSceneToPng(scene);
      const beat = (input.beat_label ?? "promo").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "promo";
      const now = /* @__PURE__ */ new Date();
      const yyyy = now.getUTCFullYear();
      const mm = String(now.getUTCMonth() + 1).padStart(2, "0");
      const uuid = crypto.randomUUID();
      const path = `${input.tenant_id}/agent/${yyyy}/${mm}/promo-${evt.id}-${beat}-${uuid}.png`;
      const { error: upErr } = await userSupabase.storage.from(BUCKET2).upload(path, png, {
        contentType: "image/png",
        upsert: false
      });
      if (upErr) {
        const svc = supabaseServiceRole();
        const retry = await svc.storage.from(BUCKET2).upload(path, png, { contentType: "image/png", upsert: false });
        if (retry.error) throw retry.error;
      }
      const signTtl = 60 * 60 * 24 * 365;
      let storedUrl;
      const { data: signed, error: signErr } = await userSupabase.storage.from(BUCKET2).createSignedUrl(path, signTtl);
      if (signErr || !signed?.signedUrl) {
        const svc = supabaseServiceRole();
        const retry = await svc.storage.from(BUCKET2).createSignedUrl(path, signTtl);
        if (retry.error || !retry.data?.signedUrl) throw signErr ?? retry.error;
        storedUrl = retry.data.signedUrl;
      } else {
        storedUrl = signed.signedUrl;
      }
      const overlayConfig = {
        canvas: { format: scene.format, width: scene.width, height: scene.height },
        overlays: promoSceneToEditorTexts(scene).map((t) => ({
          id: crypto.randomUUID(),
          type: "text",
          text: t.text,
          x: t.x,
          y: t.y,
          fontSize: t.fontSize,
          color: t.color,
          fontFamily: t.fontFamily,
          fontWeight: t.fontWeight
        }))
      };
      const fileName = input.file_name ?? `${evt.name} \u2014 ${input.beat_label ?? "Promo"}.png`;
      const label = `${input.format.charAt(0).toUpperCase()}${input.format.slice(1)} ${scene.width}x${scene.height}`;
      const { data: row, error: insErr } = await userSupabase.from("tenant_marketing_assets").insert({
        tenant_id: input.tenant_id,
        file_name: fileName,
        file_path: path,
        url: storedUrl,
        background_url: evt.image_url ?? null,
        overlay_config: overlayConfig,
        label,
        campaign_id: input.campaign_id ?? null,
        is_published: false,
        agent_source: "claude-mcp",
        proposed_by: uid,
        created_by: uid,
        notes: input.beat_label ? `Beat: ${input.beat_label}` : null
      }).select().single();
      if (insErr) throw insErr;
      return okJson(row, "asset");
    } catch (err) {
      return toolError(err, "compose_event_promo");
    }
  }
});

// supabase/functions/_shared/mcp-tools/_registry.ts
var tools = [
  get_me_default,
  list_tournaments_default,
  list_challenges_default,
  get_challenge_default,
  list_games_default,
  list_tenants_default,
  get_brand_kit_default,
  list_upcoming_events_default,
  list_platform_templates_default,
  list_tenant_assets_default,
  list_pending_agent_drafts_default,
  create_campaign_draft_default,
  update_campaign_draft_default,
  attach_tenant_asset_draft_default,
  propose_scheduled_post_default,
  update_scheduled_post_default,
  list_branded_pages_default,
  list_page_templates_default,
  propose_branded_page_default,
  propose_portal_banner_update_default,
  compose_event_promo_default
];

// src/lib/mcp/index.ts
var projectRef = "yrhwzmkenjgiujhofucx";
var mcp_default = defineMcp({
  name: "fgn-mcp",
  title: "FGN Gaming Network",
  version: "0.1.0",
  instructions: "Tools for the FGN gaming platform. Read-only: `get_me`, `list_tournaments`, `list_challenges`/`get_challenge`, `list_games`, `list_tenants`, `get_brand_kit`, `list_upcoming_events`, `list_platform_templates` (pass `tenant_id` to see per-tenant `adopted` / `adopted_asset_id`; use `universal_only=true` for platform-wide universal assets), `list_tenant_assets`, `list_pending_agent_drafts`. Marketing agent (drafts only \u2014 nothing publishes without tenant admin approval): `create_campaign_draft`, `update_campaign_draft`, `attach_tenant_asset_draft` (downloads external URLs server-side into tenant storage; use the `url` of an unadopted universal asset as `source_url` and pass its id as `source_asset_id` to localize it into the tenant library), `propose_scheduled_post`, `update_scheduled_post`. Slate runs: prefer proposing localized treatments of unadopted universal assets before generating new imagery. Each turn: call `list_pending_agent_drafts` first and revise rejected work (address feedback_note) before proposing new drafts. Use `idempotency_key` on create/propose calls so retries never duplicate.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
